version: "3.5"

services:
  mini-mysql:
    image: mysql:8.0.30
    container_name: "mini-mysql"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      # - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=minisecret
      - MYSQL_USER=mini
      - MYSQL_DATABASE=minifactory
      - MYSQL_PASSWORD=minisecret

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  dbdata:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
