version: "3.5"

services:
  mini-mysql:
    image: mysql:8.0.30
    container_name: "mini-mysql"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      # - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=minisecret
      - MYSQL_USER=mini
      - MYSQL_DATABASE=minifactory
      - MYSQL_PASSWORD=minisecret
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  dbdata:
